# Generated by Django 6.0.5 on 2026-05-08 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_department_options_alter_faculty_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_number', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('position_code', models.CharField(blank=True, max_length=20)),
                ('academic_degree', models.CharField(blank=True, choices=[('', "Yo'q"), ('phd', 'PhD'), ('dsc', 'DSc'), ('candidate', 'Fan nomzodi'), ('doctor', 'Fan doktori')], max_length=30)),
                ('academic_rank', models.CharField(blank=True, choices=[('', "Yo'q"), ('assistant', 'Assistent'), ('dotsent', 'Dotsent'), ('professor', 'Professor'), ('katta_oqituvchi', "Katta o'qituvchi")], max_length=30)),
                ('employment_form', models.CharField(choices=[('asosiy', 'Asosiy'), ('orindosh', "O'rindosh"), ('soatbay', 'Soatbay')], default='asosiy', max_length=20)),
                ('hire_date', models.DateField()),
                ('contract_number', models.CharField(blank=True, max_length=30)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('passport', models.CharField(blank=True, max_length=9)),
                ('pinfl', models.CharField(blank=True, max_length=14)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('leave', "Ta'tilda"), ('business_trip', 'Safarda'), ('inactive', 'Ishlamaydi')], default='active', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HrOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('hire', 'Ishga qabul'), ('fire', "Ishdan bo'shatish"), ('transfer', "Ko'chirish"), ('promotion', 'Lavozim oshirish'), ('salary_change', "Maosh o'zgartirish"), ('leave', "Ta'til"), ('business_trip', 'Xizmat safari'), ('bonus', 'Mukofot'), ('penalty', 'Jazo')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('effective_date', models.DateField()),
                ('signer', models.CharField(blank=True, max_length=100)),
                ('basis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('review', "Ko'rib chiqilmoqda"), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hr.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('annual', "Mehnat ta'tili"), ('sick', 'Kasallik'), ('maternity', 'Dekret'), ('unpaid', "Haq to'lanmaydigan"), ('business_trip', 'Xizmat safari'), ('study', "O'quv")], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveSmallIntegerField()),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
