# Generated by Django 6.0.5 on 2026-05-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Artikul')),
                ('category', models.CharField(choices=[('office', 'Ofis'), ('cleaning', 'Tozalash'), ('technical', 'Texnik'), ('furniture', 'Mebel'), ('food', 'Oziq-ovqat'), ('other', 'Boshqa')], default='other', max_length=15)),
                ('quantity', models.IntegerField(default=0, verbose_name='Miqdori')),
                ('unit', models.CharField(max_length=20, verbose_name='Birlik')),
                ('min_quantity', models.IntegerField(default=0, verbose_name='Minimal miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narxi')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Joylashuv')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ombor buyumi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('incoming', 'Kirim'), ('outgoing', 'Chiqim'), ('write_off', 'Hisobdan chiqarish'), ('transfer', "Ko'chirish")], max_length=15)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.warehouseitem')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'ordering': ['-created_at'],
            },
        ),
    ]
