# Generated by Django 6.0.5 on 2026-05-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('education_type', "Ta'lim turi"), ('education_form', "Ta'lim shakli"), ('payment_form', "To'lov shakli"), ('accommodation', 'Yashash joyi'), ('country', 'Davlat'), ('region', 'Viloyat'), ('district', 'Tuman'), ('nationality', 'Millat'), ('citizenship', 'Fuqarolik'), ('social_category', 'Ijtimoiy toifa'), ('student_status', 'Talaba holati'), ('gender', 'Jinsi'), ('marital_status', 'Oilaviy holat'), ('language', 'Til'), ('subject_type', 'Fan turi'), ('academic_degree', 'Ilmiy daraja'), ('academic_rank', 'Ilmiy unvon'), ('employment_form', 'Bandlik shakli'), ('custom', 'Boshqa')], db_index=True, max_length=30)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('name_uz', models.CharField(blank=True, max_length=300)),
                ('name_ru', models.CharField(blank=True, max_length=300)),
                ('name_en', models.CharField(blank=True, max_length=300)),
                ('hemis_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.referencedata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ma'lumotnoma",
                'verbose_name_plural': "Ma'lumotnomalar",
                'ordering': ['type', 'sort_order', 'name'],
                'unique_together': {('type', 'code')},
            },
        ),
    ]
