# Generated by Django 6.0.5 on 2026-05-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_referencedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hemis_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='HEMIS ID'),
        ),
        migrations.AddField(
            model_name='group',
            name='hemis_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='HEMIS ID'),
        ),
        migrations.AddField(
            model_name='semester',
            name='hemis_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='HEMIS ID'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='hemis_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='HEMIS ID'),
        ),
    ]
