export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';
export const USE_MOCK = import.meta.env.VITE_USE_MOCK !== 'false';

export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    refreshToken: '/auth/token/refresh',
  },
  core: {
    branches: '/core/branches',
    faculties: '/core/faculties',
    departments: '/core/departments',
    specialties: '/core/specialties',
    groups: '/core/groups',
    academicYears: '/core/academic-years',
    semesters: '/core/semesters',
    smsSend: '/core/sms/send',
    notificationSend: '/core/notifications/send',
  },
  students: {
    list: '/students',
    detail: (id: number) => `/students/${id}`,
    create: '/students',
    statistics: '/students/statistics',
    grades: (id: number) => `/students/${id}/grades`,
    attendance: (id: number) => `/students/${id}/attendance`,
    exportExcel: '/students/export',
    exportPdf: '/students/export-pdf',
    importExcel: '/students/import',
  },
  finance: {
    contracts: '/finance/contracts',
    contractDetail: (id: string) => `/finance/contracts/${id}`,
    contractPdf: (id: string) => `/finance/contracts/${id}/pdf`,
    contractsExportPdf: '/finance/contracts/export-pdf',
    paymentLink: (id: string) => `/finance/contracts/${id}/payment-link`,
    payments: '/finance/payments',
    scholarships: '/finance/scholarships',
    dashboard: '/finance/dashboard',
    report: '/finance/report',
    paymeCallback: '/finance/payments/payme/callback',
    clickCallback: '/finance/payments/click/callback',
  },
  hr: {
    employees: '/hr/employees',
    employeeDetail: (id: number) => `/hr/employees/${id}`,
    employeesExport: '/hr/employees/export',
    departments: '/hr/departments',
    orders: '/hr/orders',
    attendance: '/hr/attendance',
    leaves: '/hr/leaves',
    dashboard: '/hr/dashboard',
  },
  education: {
    subjects: '/education/subjects',
    schedules: '/education/schedules',
    scheduleDetail: (id: number) => `/education/schedules/${id}`,
    attendanceBulk: '/education/attendance/bulk',
    gradesBulk: '/education/grades/bulk',
    grades: '/education/grades',
    attendance: '/education/attendance',
  },
  exams: {
    list: '/education/exams',
    detail: (id: number) => `/education/exams/${id}`,
  },
  curriculum: {
    list: '/education/curriculums',
    detail: (id: number) => `/education/curriculums/${id}`,
  },
  library: {
    books: '/education/library/books',
    bookDetail: (id: number) => `/education/library/books/${id}`,
    loans: '/education/library/loans',
    returnBook: (id: number) => `/education/library/loans/${id}/return`,
  },
  alumni: {
    list: '/education/alumni',
    detail: (id: number) => `/education/alumni/${id}`,
  },
  internship: {
    list: '/education/internships',
    detail: (id: number) => `/education/internships/${id}`,
  },
  crm: {
    leads: '/crm/leads',
    leadDetail: (id: number) => `/crm/leads/${id}`,
    stats: '/crm/stats',
    bulkStatus: '/crm/leads/bulk-status',
    exportExcel: '/crm/leads/export',
  },
  teachers: {
    list: '/teachers',
    detail: (id: number) => `/teachers/${id}`,
  },
  science: {
    projects: '/science/projects',
    projectDetail: (id: number) => `/science/projects/${id}`,
    articles: '/science/articles',
    articleDetail: (id: number) => `/science/articles/${id}`,
    grants: '/science/grants',
    conferences: '/science/conferences',
    conferenceDetail: (id: number) => `/science/conferences/${id}`,
    theses: '/science/theses',
    thesisDetail: (id: number) => `/science/theses/${id}`,
    patents: '/science/patents',
    patentDetail: (id: number) => `/science/patents/${id}`,
  },
  operations: {
    tasks: '/operations/tasks',
    taskDetail: (id: number) => `/operations/tasks/${id}`,
    notifications: '/operations/notifications',
    markRead: '/operations/notifications/read',
    threads: '/operations/messages/threads',
    messages: (threadId: number) => `/operations/messages/threads/${threadId}`,
    appeals: '/operations/appeals',
    appealDetail: (id: number) => `/operations/appeals/${id}`,
    news: '/operations/news',
    newsDetail: (id: number) => `/operations/news/${id}`,
    reports: '/operations/reports/templates',
    generateReport: '/operations/reports/generate',
  },
  system: {
    users: '/system/users',
    userDetail: (id: number) => `/system/users/${id}`,
    roles: '/system/roles',
    roleDetail: (id: string) => `/system/roles/${id}`,
    permissions: '/system/permissions',
    auditLog: '/system/audit-log',
  },
  admin: {
    documents: '/admin/documents',
    documentDetail: (id: number) => `/admin/documents/${id}`,
    folders: '/admin/folders',
    analytics: '/admin/analytics',
    dictionaries: (type: string) => `/admin/dictionaries/${type}`,
    dictionaryItem: (type: string, id: number) => `/admin/dictionaries/${type}/${id}`,
  },
  infrastructure: {
    buildings: '/infrastructure/dormitory/buildings',
    rooms: '/infrastructure/dormitory/rooms',
    roomDetail: (id: number) => `/infrastructure/dormitory/rooms/${id}`,
    residents: '/infrastructure/dormitory/residents',
    equipment: '/infrastructure/equipment',
    equipmentDetail: (id: number) => `/infrastructure/equipment/${id}`,
    vehicles: '/infrastructure/transport',
    vehicleDetail: (id: number) => `/infrastructure/transport/${id}`,
  },
  warehouse: {
    items: '/warehouse/items',
    itemDetail: (id: number) => `/warehouse/items/${id}`,
    movements: '/warehouse/movements',
    stats: '/warehouse/stats',
  },
  legacy: {
    orders: '/legacy/orders',
    staffing: '/legacy/staffing',
  },
  cabinets: {
    student: '/cabinets/student',
    teacher: '/cabinets/teacher',
  },
  payroll: {
    list: '/finance/payroll',
    summary: '/finance/payroll/summary',
    process: '/finance/payroll/process',
  },
  budget: {
    categories: '/finance/budget/categories',
    summary: '/finance/budget/summary',
  },
  dashboard: {
    stats: '/dashboard',
    admin: '/dashboard/admin',
    buxgalter: '/dashboard/buxgalter',
    dekan: '/dashboard/dekan',
    oqituvchi: '/dashboard/oqituvchi',
    talaba: '/dashboard/talaba',
  },
} as const;
