# Generated by Django 6.0.5 on 2026-05-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Raqam')),
                ('date', models.DateField(verbose_name='Sana')),
                ('type', models.CharField(choices=[('hire', 'Qabul'), ('fire', "Bo'shatish"), ('reward', 'Mukofot'), ('leave', "Ta'til"), ('penalty', 'Jazo')], max_length=10)),
                ('type_label', models.CharField(blank=True, max_length=50)),
                ('employee_name', models.CharField(max_length=200, verbose_name='Xodim')),
                ('department', models.CharField(max_length=200, verbose_name="Bo'lim")),
                ('content', models.TextField(blank=True, verbose_name='Mazmun')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('archived', 'Arxivlangan')], default='archived', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eski buyruq',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.CharField(max_length=200, verbose_name="Bo'lim")),
                ('position_name', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('total_slots', models.IntegerField(default=1, verbose_name='Jami birliklar')),
                ('filled_slots', models.IntegerField(default=0, verbose_name='Band birliklar')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Maosh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shtat birligi',
                'ordering': ['department_name', 'position_name'],
            },
        ),
    ]
