# Generated by Django 6.0.5 on 2026-05-10 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('floors', models.IntegerField(default=1, verbose_name='Qavatlar soni')),
                ('total_rooms', models.IntegerField(default=0, verbose_name='Xonalar soni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yotoqxona binosi',
                'verbose_name_plural': 'Yotoqxona binolari',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Inventar raqami')),
                ('category', models.CharField(max_length=100, verbose_name='Turkum')),
                ('location', models.CharField(max_length=200, verbose_name='Joylashuv')),
                ('responsible_person', models.CharField(max_length=200, verbose_name='Javobgar shaxs')),
                ('purchase_date', models.DateField(verbose_name='Sotib olingan sana')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('working', 'Ishlamoqda'), ('repair', "Ta'mirda"), ('written_off', 'Hisobdan chiqarilgan'), ('storage', 'Omborda')], default='working', max_length=15)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jihoz',
                'verbose_name_plural': 'Jihozlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('year', models.IntegerField(verbose_name='Ishlab chiqarilgan yil')),
                ('driver_name', models.CharField(max_length=200, verbose_name='Haydovchi')),
                ('route', models.CharField(blank=True, max_length=300, verbose_name="Yo'nalish")),
                ('status', models.CharField(choices=[('available', 'Faol'), ('in_use', 'Foydalanishda'), ('repair', "Ta'mirda"), ('decommissioned', 'Nofaol')], default='available', max_length=20)),
                ('mileage', models.IntegerField(default=0, verbose_name='Yurgan masofasi')),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transport vositalari',
            },
        ),
        migrations.CreateModel(
            name='DormRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='Xona raqami')),
                ('floor', models.IntegerField(default=1, verbose_name='Qavat')),
                ('capacity', models.IntegerField(default=4, verbose_name="Sig'imi")),
                ('occupied', models.IntegerField(default=0, verbose_name='Band')),
                ('status', models.CharField(choices=[('available', 'Bosh'), ('partial', "Qisman to'la"), ('full', "To'la"), ('repair', "Ta'mirda")], default='available', max_length=15)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='infrastructure.dormbuilding')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yotoqxona xonasi',
                'unique_together': {('building', 'number')},
            },
        ),
    ]
