# Generated by Django 6.0.5 on 2026-05-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direction', models.CharField(max_length=200, verbose_name="Yo'nalish")),
                ('source', models.CharField(choices=[('website', 'Veb-sayt'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('referral', 'Tavsiya'), ('event', 'Tadbir'), ('call', "Qo'ng'iroq")], default='website', max_length=20, verbose_name='Manba')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('interested', 'Qiziqgan'), ('applied', "Ariza to'ldirdi"), ('enrolled', "O'qishga qabul qilindi"), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='Oxirgi aloqa')),
                ('next_contact_date', models.DateField(blank=True, null=True, verbose_name='Keyingi aloqa')),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lid',
                'verbose_name_plural': 'Lidlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
