# Generated by Django 6.0.5 on 2026-05-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
        ('education', '0002_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name="O'quv yili (1–4)")),
                ('total_credits', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.specialty')),
            ],
            options={
                'ordering': ['specialty', 'year'],
                'unique_together': {('specialty', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('hours_total', models.PositiveSmallIntegerField(default=0)),
                ('is_elective', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.curriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject')),
            ],
            options={
                'ordering': ['semester_number', 'subject__name'],
                'unique_together': {('curriculum', 'subject', 'semester_number')},
            },
        ),
    ]
