# Generated by Django 6.0.5 on 2026-05-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_curriculum_curriculumsubject'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('textbook', 'Darslik'), ('reference', "Ma'lumotnoma"), ('fiction', 'Badiiy'), ('periodical', 'Davriy nashr'), ('other', 'Boshqa')], default='textbook', max_length=20)),
                ('copies_total', models.PositiveSmallIntegerField(default=1)),
                ('copies_available', models.PositiveSmallIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Berilgan'), ('returned', 'Qaytarilgan'), ('overdue', "Muddati o'tgan")], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='education.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='students.student')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
