# Generated by Django 6.0.5 on 2026-05-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
        ('education', '0004_book_bookloan'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveSmallIntegerField()),
                ('workplace', models.CharField(blank=True, max_length=300)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('employed', 'Ishlamoqda'), ('studying', "O'qimoqda"), ('unemployed', 'Ishlamayapti'), ('unknown', "Noma'lum")], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='core.faculty')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='core.specialty')),
            ],
            options={
                'verbose_name_plural': 'alumni',
                'ordering': ['-graduation_year', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('internship_type', models.CharField(choices=[('production', 'Ishlab chiqarish'), ('educational', "O'quv"), ('pre_graduation', 'Bitiruvchi')], default='production', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('active', 'Jarayonda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='planned', max_length=20)),
                ('report_submitted', models.BooleanField(default=False)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.student')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
