# Generated by Django 6.0.5 on 2026-05-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_subject_hemis_id'),
        ('students', '0003_student_hemis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Kutmoqda'), ('notified', 'Xabardor qilindi'), ('cancelled', 'Bekor qilindi')], default='waiting', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='education.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_queue', to='students.student')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('book', 'student', 'status')},
            },
        ),
    ]
