# Generated by Django 6.0.5 on 2026-05-08 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_department_options_alter_faculty_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('course', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr')], default='bakalavr', max_length=20)),
                ('education_type', models.CharField(choices=[('kontrakt', 'Kontrakt'), ('grant', 'Grant')], max_length=20)),
                ('payment_form', models.CharField(choices=[('kontrakt', 'Kontrakt'), ('grant', 'Grant')], max_length=20)),
                ('education_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], default='kunduzgi', max_length=20)),
                ('enrollment_date', models.DateField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('academic_leave', "Akademik ta'til"), ('expelled', "O'chirilgan"), ('graduated', 'Bitirgan'), ('transferred', "Ko'chirilgan")], db_index=True, default='active', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('passport', models.CharField(blank=True, max_length=9)),
                ('pinfl', models.CharField(blank=True, max_length=14)),
                ('address', models.TextField(blank=True)),
                ('avg_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['group', 'status'], name='students_st_group_i_c751b1_idx'), models.Index(fields=['student_id_number'], name='students_st_student_242a3a_idx')],
            },
        ),
    ]
