# Generated by Django 6.0.5 on 2026-05-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('category', models.CharField(choices=[('passport', 'Pasport'), ('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('contract', 'Kontrakt'), ('photo', 'Fotosurat'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
