# Generated by Django 6.0.5 on 2026-05-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hemis_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='HEMIS ID'),
        ),
    ]
